### ISSUE TITLE
[STYLE]주류 사전 페이지 생성

### ISSUE THREAD

**Issue by SunYerim** [pknu-wap/2023_1_WAT_BeJuRyu#58]
## 📑 작업 사항 
주류 사전 페이지를 생성하고 대략적인 UI를 구현한다.
그리고 MOCK 데이터를 활용해 화면 배치도 고민해본다.

## To-do
- [x] 주류 사전 페이지 생성
- [ ] UI 구현
- [ ] Mock 데이터 활

# #✔️ 기타사항
브랜치 에러 이슈로 인해... 다시 ISSUE를 팠습니다

**Comment by SunYerim** [comment]
주류 추천페이지가 아니고 주류 사전페이지 생성으로 commit 했어야했는디

**Comment by jeongjaino** [comment]
저도 그런 실수 많이하는데, git log와 git rebase를 통해 이미 푸쉬한 커밋 메시지 수정할 수 있어요! https://data-study-clip.tistory.com/237
